### ISSUE TITLE
Ruby 2 required?

### ISSUE THREAD

**Issue by ike18t** [DAddYE/fiddler#1]
I'm trying to use your leveldb gem in my app running on a Raspberry Pi.  Unfortunately it doesn't appear that fiddle supports the arm architecture for ruby greater than 1.9.3. http://ftp.jaist.ac.jp/pub/NetBSD/packages/current-src/pkgsrc/devel/ruby-fiddle/README.html 
Is there truly a ruby >= 2.0 dependency?

Thanks!
ike18t

**Comment by DAddYE** [comment]
IIRC, on ruby 1.8 there were [DL](http://ruby-doc.org/stdlib-1.8.7/libdoc/dl/rdoc/DL/Handle.html) however they totally change the api, so I'm not sure what kind of effort is needed to allow the compatibility.
